####### Lesson 01: Introduction to Python #########

# Introduction to Python Bytecode
# Python bytecode is the intermediate representation of Python code that is generated by the Python compiler. When you write Python code, it is first compiled into bytecode, which is then executed by the Python interpreter.

# Example of Python Bytecode
def add(a, b):
    return a + b

result = add(5, 3)
print(result)

# greet() method
def greet(name):
    print(f"Hello, {name}! How are you?")

# Method call
greet("Nabila")

# Indentation in Python
if True:
    print("Hello, World!")
    print("This is a block of code")

# with greet
def greet(name: str):
    print("Hello, " + name + "!")


###### ************ #######